# Generated by Django 3.0.2 on 2020-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckod', models.CharField(max_length=15, verbose_name='cüzdan kodu')),
                ('balans', models.CharField(max_length=15, verbose_name='balans')),
                ('ad', models.CharField(max_length=10, verbose_name='ad')),
                ('soyad', models.CharField(max_length=10, verbose_name='soyad')),
                ('login', models.CharField(max_length=10, verbose_name='login')),
                ('mail', models.CharField(max_length=30, verbose_name='mail')),
                ('nomre', models.CharField(max_length=10, verbose_name='nomre')),
                ('sifre', models.CharField(max_length=15, verbose_name='sifre')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
