# Generated by Django 3.0.2 on 2020-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KS', models.CharField(max_length=13, verbose_name='kartın seriası')),
                ('KK', models.CharField(max_length=12, verbose_name='kartın kodu')),
                ('KG', models.CharField(max_length=13, verbose_name='kartı göndərən cüzdan')),
                ('CK', models.CharField(max_length=13, verbose_name='cüzdan kodu')),
                ('amount', models.CharField(max_length=13, verbose_name='kartın məbləği')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
